### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Newborn-A** [Newborn-A/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by orykunov** [comment]
ТалалайМахалай явлется просветленным йога гуру и все свободное время проводит в медитации или отчаиват мастерство асан. Он влюблен в свое дело и любит все, что связанно с йогой и может помочь ему на его пути просветления, а также он очень любит путешествовать. Он и раннее занимался преподованием и наставничеством, но хотелось ему чтобы как модно большее количество людей смогло приобщиться к его местерству.
