### ISSUE TITLE
Скласти блок контактної інформаці

### ISSUE THREAD

**Issue by Newborn-A** [Newborn-A/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by orykunov** [comment]
Since TallalayMahalay doesn't familiar with social, he has a friend Alex, who you can contact with regarding to any questions:
https://www.facebook.com/alexey.rikunov.5
Email: taialexchi@gmail.com
Phone: +380988512931
