### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Newborn-A** [Newborn-A/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by orykunov** [comment]
2002-2008 PRYAZOVSKYI STATE TECHNICAL UNIVERSITY Metallurgy – Ferrous and non-ferrous metals 

June 2005 – December 2008 UNITRADE GROUP - SELLER/RETAIL STORE SUPERVISOR
Control and organizing work routine processes in the retail store. Conducting monthly reports. Dealing with complaints. 
Generation positive atmosphere and encouraging high productivity.

January 2009 – December 2009 MARCOM GROUP – SALES REPRESENTATIVE
Increasing product range in stores and control merchandising standards, looking for new potential clients, determine discount rates. Realization delivering and payment control, dealing with complaints.

October 2010 – August 2012 AZOVELECTROSTAL- MOLDING MACHINE OPERATOR
Operating molding machine, quality control.    

July 2013-August 2019 STARWOOD HOTELS AND RESORTS Bar Supervisor
Creating emotional connections with guests, dealing with complaints. Identification of additional revenue opportunities. Maintenance positive teamwork, coaching, and training. Daily data collection and reporting. 

March 2017- April 2019 - ABIE training center- English Teacher
Berlitz Corporation  - Business English Trainer (part-time)
Developing and conducting English lessons for kids. Encouraging and motivating them. Participating in school promotions and activities.

April 2021 InfuseMedia - CampaignManager - till now

Training:
Skill Train the Trainer Program – St. Regis, Abu Dhabi – 2015
Harvard Manage Mentor Online Courses - 2016
Teaching English As Foreign Language Course (TEFL) - 2018
JavaRush 1-20 levels  - 2020
Git Geekbrains  - 2021

 Personal Skills:
-	Enthusiastic, highly motivated, and proactive attitude to work
-	Strong orientation on the superior quality of customer service
-	Self-motivated and oriented to constant self-development and growth 
-	Like sports, reading, traveling
