### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Newborn-A** [Newborn-A/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by orykunov** [comment]
Sometimes in your life, you reach the point where you should choose the path you like. Some people go all way straight, some change their directions to find something they like. I'm not scared to dare, knowing it's going to be hard, here's my straight. I like different kinds of moving activities, like skating, swimming, rafting/ Recently, I have discovered yoga for myself, which I also like to do, as an alternative all day sitting in front of a screen job.
